name: Deploy changes
on:
  push:
    branches:
      - main
jobs:
  # Deploy changed code to AWS (currently dummy code)
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.9'
      #   cache: 'pip' # don't need python yet, so disabling cache
      # Use the AWS credentials we have set in our GH Action secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.GHA_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.GHA_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Deploy layer
        run: |
          cd deploy
          bash deploy_layer.sh
      - name: Get latest layer version and run
        run: aws lambda list-layer-versions --layer-name quadball --region us-west-2 --query 'LayerVersions[0].LayerVersionArn' | bash deploy_lambdas.sh


