name: Run Pytest
on:
  push:
    branches:
      - main
jobs:
  # Deploy changed code to AWS (currently dummy code)
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.10'
          cache: 'pip'
      # Use the AWS credentials we have set in our GH Action secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.GHA_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.GHA_AWS_SECRET_ACCESS_KEY }}
      - run: aws s3 list-buckets
