# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: team.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nteam.proto\x12\tmodels.db\"m\n\x04Team\x12\x0f\n\x07team_id\x18\x01 \x01(\t\x12\x19\n\x11team_abbreviation\x18\x02 \x01(\t\x12\x11\n\tteam_name\x18\x03 \x01(\t\x12&\n\tteam_type\x18\x04 \x01(\x0e\x32\x13.models.db.TeamType*x\n\x08TeamType\x12\x14\n\x10TEAM_TYPE_UNKOWN\x10\x00\x12\x15\n\x11TEAM_TYPE_COLLEGE\x10\x01\x12\x12\n\x0eTEAM_TYPE_CLUB\x10\x02\x12\x14\n\x10TEAM_TYPE_REGION\x10\x03\x12\x15\n\x11TEAM_TYPE_COUNTRY\x10\x04\x62\x06proto3')

_TEAMTYPE = DESCRIPTOR.enum_types_by_name['TeamType']
TeamType = enum_type_wrapper.EnumTypeWrapper(_TEAMTYPE)
TEAM_TYPE_UNKOWN = 0
TEAM_TYPE_COLLEGE = 1
TEAM_TYPE_CLUB = 2
TEAM_TYPE_REGION = 3
TEAM_TYPE_COUNTRY = 4


_TEAM = DESCRIPTOR.message_types_by_name['Team']
Team = _reflection.GeneratedProtocolMessageType('Team', (_message.Message,), {
  'DESCRIPTOR' : _TEAM,
  '__module__' : 'team_pb2'
  # @@protoc_insertion_point(class_scope:models.db.Team)
  })
_sym_db.RegisterMessage(Team)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEAMTYPE._serialized_start=136
  _TEAMTYPE._serialized_end=256
  _TEAM._serialized_start=25
  _TEAM._serialized_end=134
# @@protoc_insertion_point(module_scope)
